### PR TITLE
Add multiple key arguments to dissoc.

### LINKED ISSUE #256: dissoc should accept multiple key names
In Clojure, `(dissoc m :a :b :c)` removes `:a`, `:b` and `:c` from a map.

I wanted Toolz to do the analogous thing today, but `dissoc` is fixed arity 2 in Toolz.

### PR DESCRIPTION
**Pull request by eigenhombre**
Fixes #256 .  @mrocklin @eriknw do you want the docstring extended to include e.g. a 3-ary example?

### CODE REVIEW

**Comment by mrocklin** [comment]
Extended docstring would be ideal.

**Comment by eigenhombre** [comment]
@mrocklin added docstring example `dissoc`ing two keys.

**Comment by mrocklin** [comment]
I'm +1 on this if @eriknw is ok with it.

**Comment by eriknw** [comment]
+1.  Nice improvement.

**Comment by mrocklin** [comment]
@eigenhombre care to do the honors?  It's been a while since you exercised your commit rights in these parts :)

Good to have you back (even if only for a little while.)

**Comment by eigenhombre** [comment]
Wow, I feel so powerful again!  Thanks @eriknw @mrocklin .

**Pull request merged**
