### PR TITLE
Add Recipes section to API page

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by gliptak** [comment]
@eriknw please approve running workflows

**Comment by gliptak** [comment]
@eriknw please review

**Comment by eriknw** [comment]
Thanks @gliptak!  I didn't realize recipes was missing here.  I would probably put "Recipes" section after `Dicttoolz`.

And sorry for my delay.  Sometimes there aren't enough hours in the day!

**Comment by gliptak** [comment]
@eriknw no worries. updated

**Comment by eriknw** [comment]
Thanks @gliptak, and double-thanks for your patience! :)

**Pull request merged**
