### PR TITLE
Sliding_window simplified and optimized.

### PR DESCRIPTION
**Pull request by coady**

### CODE REVIEW

**Comment by llllllllll** [comment]
Can you show a bench mark where this is optimized, does this behavior hold for various lengths of sequences and windows?

I also know @eriknw does not want to use `tee` in toolz for memory concerns, I think the current impl is pretty clear and efficient but I am sure the developers are open to a good performance improvement!

**Comment by coady** [comment]
From `bench/test_sliding_window.py`:
```
In []: seq = range(1000000)

In []: %timeit list(old_sliding_window(2, seq))
1 loop, best of 3: 293 ms per loop

In []: %timeit list(old_sliding_window(3, seq))
1 loop, best of 3: 296 ms per loop

In []: %timeit list(new_sliding_window(2, seq))
10 loops, best of 3: 102 ms per loop

In []: %timeit list(new_sliding_window(3, seq))
10 loops, best of 3: 114 ms per loop
```

As for memory, `tee` only caches as much as necessary, which in this case is the same size as the tuples themselves.

**Comment by eriknw** [comment]
Nice!

Here are a few more benchmarks using `benchtoolz`.  To summarize the results, @coady's implementation is better except when `n >= 100` or when `len(seq)` is within a factor of 4 or so of `n`.  I verified that the use of `tee` here does not consume more memory than necessary.

```python
import collections
import itertools
from toolz.compatibility import zip


def sliding_windowtoolz(n, seq):
    it = iter(seq)
    # An efficient FIFO data structure with maximum length
    d = collections.deque(itertools.islice(it, n), n)
    if len(d) != n:
        raise StopIteration()
    d_append = d.append
    for item in it:
        yield tuple(d)
        d_append(item)
    yield tuple(d)


def sliding_window1(n, seq):
    return zip(*(itertools.islice(it, i, None)
               for i, it in enumerate(itertools.tee(seq, n))))
```
```python
from cytoolz.utils import consume

seq1 = list(range(1))
seq10 = list(range(10))
seq100 = list(range(100))
seq1000 = list(range(1000))
seq10000 = list(range(10000))
seq100000 = list(range(100000))


def bench_sliding_window1_1():
    consume(sliding_window(1, seq1))

def bench_sliding_window1_10():
    consume(sliding_window(1, seq10))

def bench_sliding_window1_100():
    consume(sliding_window(1, seq100))

def bench_sliding_window1_1000():
    consume(sliding_window(1, seq1000))

def bench_sliding_window1_10000():
    consume(sliding_window(1, seq10000))

def bench_sliding_window3_10():
    consume(sliding_window(3, seq10))

def bench_sliding_window3_100():
    consume(sliding_window(3, seq100))

def bench_sliding_window3_1000():
    consume(sliding_window(3, seq1000))

def bench_sliding_window3_10000():
    consume(sliding_window(3, seq10000))

def bench_sliding_window10_10():
    consume(sliding_window(10, seq10))

def bench_sliding_window10_100():
    consume(sliding_window(10, seq100))

def bench_sliding_window10_1000():
    consume(sliding_window(10, seq1000))

def bench_sliding_window10_10000():
    consume(sliding_window(10, seq10000))

def bench_sliding_window30_100():
    consume(sliding_window(30, seq100))

def bench_sliding_window30_1000():
    consume(sliding_window(30, seq1000))

def bench_sliding_window30_10000():
    consume(sliding_window(30, seq10000))

def bench_sliding_window30_100000():
    consume(sliding_window(30, seq100000))

def bench_sliding_window100_100():
    consume(sliding_window(100, seq100))

def bench_sliding_window100_1000():
    consume(sliding_window(100, seq1000))

def bench_sliding_window100_10000():
    consume(sliding_window(100, seq10000))

def bench_sliding_window100_100000():
    consume(sliding_window(100, seq100000))

def bench_sliding_window300_1000():
    consume(sliding_window(300, seq1000))

def bench_sliding_window300_10000():
    consume(sliding_window(300, seq10000))

def bench_sliding_window300_100000():
    consume(sliding_window(300, seq100000))
```
**Relative time:**

|        __Bench__ \ __Func__ | __1__ | __toolz__ |
| ---------------------------:|:-----:|:---------:|
|        __sliding_window1_1__ |  2.2  |   __1__   |
|       __sliding_window1_10__ | __1__ |    1.27   |
|      __sliding_window1_100__ | __1__ |    4.88   |
|     __sliding_window1_1000__ | __1__ |    7.85   |
|    __sliding_window1_10000__ | __1__ |    8.46   |
|       __sliding_window3_10__ |  1.24 |   __1__   |
|      __sliding_window3_100__ | __1__ |    3.17   |
|     __sliding_window3_1000__ | __1__ |    4.77   |
|    __sliding_window3_10000__ | __1__ |    5.07   |
|      __sliding_window10_10__ |  5.35 |   __1__   |
|     __sliding_window10_100__ | __1__ |    1.68   |
|    __sliding_window10_1000__ | __1__ |    2.42   |
|   __sliding_window10_10000__ | __1__ |    2.55   |
|     __sliding_window30_100__ |  1.14 |   __1__   |
|    __sliding_window30_1000__ | __1__ |    1.36   |
|   __sliding_window30_10000__ | __1__ |    1.42   |
|  __sliding_window30_100000__ | __1__ |    1.42   |
|    __sliding_window100_100__ |  22.5 |   __1__   |
|   __sliding_window100_1000__ |  1.06 |   __1__   |
|  __sliding_window100_10000__ |  1.01 |   __1__   |
| __sliding_window100_100000__ |  1.01 |   __1__   |
|   __sliding_window300_1000__ |  1.48 |   __1__   |
|  __sliding_window300_10000__ |  1.32 |   __1__   |
| __sliding_window300_100000__ |  1.32 |   __1__   |

**Comment by eriknw** [comment]
The following is surprisingly good for `n >= 20`:
```python
def sliding_window2(n, seq):
    it = iter(seq)
    t = tuple(itertools.islice(it, n))
    if len(t) != n:
        raise StopIteration()
    yield t
    for item in it:
        t = t[1:] + (item,)
        yield t
```

**Comment by eriknw** [comment]
I'm actually a little surprised how well `itertools.tee` performs here.  When I've tried to use `tee` in the past, I've been underwhelmed.

Here is a slight variation of your approach that trades conciseness for speed:
```python
def sliding_window3(n, seq):
    iters = itertools.tee(seq, n)
    for i, it in enumerate(iters):
        tuple(itertools.islice(it, i))
    return zip(*iters)
```
and some results:

**Relative time:**

|        __Bench__ \ __Func__ | __1__  | __2__  | __3__  | __toolz__ |
| ---------------------------:|:------:|:------:|:------:|:---------:|
|    __sliding_window2_10E6__ | *1.28* |  4.75  | __1__  |    7.88   |
|    __sliding_window3_10E6__ | *1.29* |  3.81  | __1__  |    6.45   |
|    __sliding_window5_10E6__ | *1.34* |  2.99  | __1__  |    5.11   |
|   __sliding_window10_10E6__ | *1.56* |  2.35  | __1__  |    3.87   |
|   __sliding_window30_10E6__ |  1.66  | *1.44* | __1__  |    2.35   |
|  __sliding_window100_10E6__ |  1.72  | *1.13* | __1__  |    1.69   |
|  __sliding_window300_10E6__ |  2.2   | __1__  | *1.25* |    1.67   |

This is a significant improvement, especially for small `n`.

I like getting optimization (and simplification) PRs, and am impressed with this one.  Thanks, @coady!  Would you like to add yourself to AUTHORS.md?

**Comment by coady** [comment]
> for i, it in enumerate(iters):
        tuple(itertools.islice(it, i))

This can't be right.  The tuples are discarded and the `zip` result will be empty.

Updated authors, thx.

**Comment by eriknw** [comment]
>> ```
for i, it in enumerate(iters):
    tuple(itertools.islice(it, i))
```

> This can't be right. The tuples are discarded and the zip result will be empty.

The point is to discard elements from the beginning of the `tee`ed iterators.  As surprising as it may seem, iterating over `itertools.islice(it, i, None)` as done in your original implementation results in a noticeable slowdown especially for large `n`.  By discarding some elements at the beginning, we can iterate over the iterators from `tee` directly.  Perhaps we could make this more obvious:
```python
In [1]: import collections
   ...: import itertools
   ...: from toolz import take
   ...: from toolz.compatibility import zip
   ...: 
   ...: def sliding_window3(n, seq):
   ...:     iters = itertools.tee(seq, n)
   ...:     for i, it in enumerate(iters):
   ...:         collections.deque(take(i, it), 0)
   ...:     return zip(*iters)
   ...: 

In [2]: list(sliding_window3(3, range(5)))
Out[2]: [(0, 1, 2), (1, 2, 3), (2, 3, 4)]
```

**Comment by coady** [comment]
Ah, I missed the change to the `islice` call;  unfortunate that it adds so much overhead.  So now it's just down to a general idiom for iteration while ignoring the result.  There's always:
```
for _ in itertools.islice(it, i):
    pass
```

**Comment by llllllllll** [comment]
if you want to do that you should force with a `deque` of maxlen 0 to pull the loop into C ;)

**Comment by coady** [comment]
So just to summarize, @eriknw's optimization was to remove `islice` from the main zip iteration.  I'm not convinced using a `deque` in this case is significant, but if there's agreement that it's a perfectly readable idiom for "exhaust an iterable" anyway, then why not.

**Comment by snth** [comment]
Hi,

I love the `toolz` package and am trying to use it more and more. The `sliding_window` function is a great start but often there are great efficiency gains by processing only the update to the sliding window rather than the whole window, like for example when calculating rolling sums or means. So I'm wondering whether we could add a `slideby` function in the spirit of `reduceby` or `accumulate`?

I wrote a basic one that is based off the `sliding_window` function:

```python
from cytoolz import sliding_window, first, last

def slideby0(n, seq, update=None, init=None):
    windows = sliding_window(n, seq)
    initseq = first(windows)
    if callable(init):
        state = init(initseq)
    elif init is not None:
        state = init
    else:
        state = initseq
    leaving = first(initseq)
    yield state
    for window in windows:
        entering = last(window)
        if update is not None:
            state = update(entering, leaving, state)
        else:
            state = state[1:] + (entering,)
        yield state
        leaving = first(window)
```

After finding this thread and seeing @eriknw 's version of `sliding_window` above I came up with the following:
```python
from itertools import tee, islice, izip

def slideby(n, seq, update=None, init=None):
    it = iter(seq)
    front, back = tee(it, 2)
    initseq = tuple(islice(front, n))
    if init is None:
        state = initseq
    elif callable(init):
        state = init(initseq)
    else:
        state = init
    yield state
    for entering, leaving in izip(front, back):
        if update is None:
            state = state[1:]+(entering,)
        else:
            state = update(entering, leaving, state)
        yield state
```
This has the advantage that it allows us to reproduce the behaviour of `sliding_window` when the `update` and `init` parameters are omitted but allows for custom implementations of `update` and `init` where efficiency matters.
```python
from toolz import sliding_window as py_sliding_window

print(list(py_sliding_window(3, range(5))))
print(list(slideby(3, range(5))))
```
```
[(0, 1, 2), (1, 2, 3), (2, 3, 4)]
[(0, 1, 2), (1, 2, 3), (2, 3, 4)]
```

The basic sliding window performance is better than the `pytoolz` version on my system (version 0.7.2) and is not far off the `cytoolz` version. I haven't tested your new improved version though.
```python
import toolz
print(toolz.__version__)
W, N = 250, 10000
%timeit list(cy_sliding_window(W, range(N)))
%timeit list(py_sliding_window(W, range(N)))
%timeit list(slideby(W, range(N)))
```
```
0.7.2
10 loops, best of 3: 18.9 ms per loop
10 loops, best of 3: 31.9 ms per loop
10 loops, best of 3: 23.4 ms per loop
```
However the main point is really to allow for efficient implementations of rolling operations and here the algorithmic improvements far outweigh any cython speedups.
```python
# Rolling sums
from cytoolz import sliding_window as cy_sliding_window
print(map(sum, py_sliding_window(3, range(5))))
print(map(sum, cy_sliding_window(3, range(5))))
print(list(slideby(3, range(5), update=lambda e, l, s: s+e-l, init=sum)))

W, N = 250, 10000
%timeit map(sum, py_sliding_window(W, range(N)))
%timeit map(sum, cy_sliding_window(W, range(N)))
%timeit list(slideby(W, range(N), update=lambda e, l, s: s+e-l, init=sum))
```
```
[3, 6, 9]
[3, 6, 9]
[3, 6, 9]
10 loops, best of 3: 36.5 ms per loop
10 loops, best of 3: 24.7 ms per loop
100 loops, best of 3: 2.21 ms per loop
```
```python
# Rolling means
print(list(py_sliding_window(3, range(5))))
print(map(np.mean, py_sliding_window(3, range(5))))
print(map(np.mean, cy_sliding_window(3, range(5))))
print(list(slideby(3, range(5), update=lambda e, l, s: (s*3+e-l)/3, init=np.mean)))

W, N = 250, 10000
%timeit map(np.mean, py_sliding_window(W, range(N)))
%timeit map(np.mean, cy_sliding_window(W, range(N)))
%timeit list(slideby(W, range(N), update=lambda e, l, s: (s*W+e-l)/W, init=np.mean))
```
```
[(0, 1, 2), (1, 2, 3), (2, 3, 4)]
[1.0, 2.0, 3.0]
[1.0, 2.0, 3.0]
[1.0, 2.0, 3.0]
1 loops, best of 3: 331 ms per loop
1 loops, best of 3: 307 ms per loop
100 loops, best of 3: 9.42 ms per loop
```
So while I could just use my own implementation, it would be great if this could be integrated into the `toolz` package to get the assurance and reliability from the testing, optimisation and documentation that make this package great!

**Comment by mrocklin** [comment]
In principle the idea of an update-based sliding window function makes sense to me.  I recommend opening another issue for it for API discussion.

**Comment by snth** [comment]
Thanks @mrocklin . I've opened issue #322.

**Comment by eriknw** [comment]
Let's get this in.  Merging.

Thanks, @coady!  Do you have any more tricks up your sleeves?

**Pull request merged**
