### PR TITLE
Add tests for pluck with default, non-None

### PR DESCRIPTION
**Pull request by jcrist**
Needed for https://github.com/pytoolz/cytoolz/pull/82 (pluck with default would fail for non-None defaults).

### CODE REVIEW

**Comment by llllllllll** [comment]
should we continue to test the `None` case alongside the `0` case?

**Comment by jcrist** [comment]
I don't think it's necessary (non-None was the edge case, due to getattr failures). Happy to change though.

**Comment by llllllllll** [comment]
I see, that seems fine then. I just wanted to make sure that wasn't also an interesting case for some reason

**Comment by eriknw** [comment]
lgtm.  thanks!

**Pull request merged**
