### PR TITLE
Add `mkpipe` function

### PR DESCRIPTION
**Pull request by tomxtobin**
`mkpipe` ("make pipe") is like `compose`, but the functions are applied left-to-right,
like the `pipe` function.

I know this is a trivial addition, logically speaking, but I find it much more natural to think of function composition as applying the functions left-to-right, as a series of operations, rather than right-to-left -- just like Unix pipelines and the toolz `pipe` function. Various libraries and functional languages (e.g., fn.py, F#) make both kinds of function composition available. And for what it's worth, I find myself defining this function in every project I use toolz in. I appreciate that we want to keep the toolz namespace from growing without bound, but this seems to be a natural and useful fit between `compose` and `pipe`.

### CODE REVIEW

**Comment by eriknw** [comment]
Shiny.  Any other ideas for what to name this operation?  What about adding a `reverse=` keyword argument to compose, so mkpipe becomes `mkpipe = curry(compose, reverse=True)`?

**Comment by tomxtobin** [comment]
Does this PR still have a chance, or should I withdraw it? I was pruning my clones and noticed it hadn't been merged or explicitly rejected.

**Comment by mrocklin** [comment]
In the current state I'm somewhat against this change.  I agree that something should be done, but I'm not sure that this is the ideal solution.  Should we close?

**Comment by tomxtobin** [comment]
Sure, I'll go ahead and close.

**Pull request closed without merging**
