### PR TITLE
Add an implementation of unzip

### PR DESCRIPTION
**Pull request by davidshepherd7**
Here's the unzip implementation I described in #239 cleaned up and with documentation.

I'm still concerned about `tee`'s memory usage as it could result in difficult-to-debug high memory usage. However I don't currently have any other ideas that would allow lazyness.

### CODE REVIEW

**Comment by eriknw** [comment]
I think it will be more convenient if `unzip` returns a tuple, not an iterator.  I also think this will encourage more idiomatic use, since all iterators should be consumed at a similar rate to limit the impact of `tee`.

I'm less concerned about having ultimate flexibility with being able to handle an infinite number of iterables with infinite length.  How would one operate on that effectively?  I don't know (but maybe answering that will reveal how to limit the impact of `tee`).  Anyway, there is a balance to be had between flexibility and convenience.

I'd like to merge this.  Do you agree about returning a tuple?

**Comment by davidshepherd7** [comment]
I changed it to return a tuple, and also fixed a bug I came across with empty iterators. Tests pass on my machine (python2 and 3) so it *should* be ok to merge.

**Comment by davidshepherd7** [comment]
Any more thoughts on merging this?

**Comment by eriknw** [comment]
> Any more thoughts on merging this?

Yeah, my bad.  I think I stretch myself too thinly at times.

This is good to go.  Thanks, @davidshepherd7!

**Comment by davidshepherd7** [comment]
> Yeah, my bad. I think I stretch myself too thinly at times.

I completely understand. :+1:

**Pull request merged**
