### PR TITLE
Add generator

### PR DESCRIPTION
**Pull request by jakirkham**
Adds a function that returns a generator type from any iterable.

Note: This ends up being slightly faster in terms of construction time than returning a generator expression.

### CODE REVIEW

**Comment by llllllllll** [comment]
I am not sure I understand why you need this function? Is this not just `iter`?

**Comment by jakirkham** [comment]
Wanted access to the generator [methods]( https://docs.python.org/2/reference/expressions.html#generator-iterator-methods ). Though this probably should provide an option to use the underlying generator's methods if provided. So let's table this until I can look at it again.

**Comment by llllllllll** [comment]
That looks like `coiter` from [cotoolz](https://github.com/llllllllll/cotoolz):

```
In [1]: from cotoolz import coiter

In [2]: coiter?
Init signature: coiter()
Docstring:     
A wrapper around standard iterators that allows them to
respond to the coroutine protocol.

If the wrapped iterable is a coroutine, then the coroutine
methods will delegate to the inner coroutine.

Paramaters
----------
it : iterable
    The iterable to wrap.

Methods
-------
send(value)
    Emulating sending a value into the iterator.
throw(exc) or throw(type, arg, traceback)
    Emulates throwing an exception into the iterator.
close()
    Emulates closing the iterator.
File:           ~/projects/python/cotoolz/cotoolz/_coiter.cpython-34m.so
Type:           type

In [3]: a = coiter([1, 2, 3])

In [4]: a.send(None)
Out[4]: 1

In [5]: a.throw(ValueError())
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-f956cf9c1483> in <module>()
----> 1 a.throw(ValueError())

ValueError: 

In [6]: a.close()

In [7]: next(a)
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-7-3f6e2eea332d> in <module>()
----> 1 next(a)

StopIteration: 
```

**Comment by jakirkham** [comment]
Ok, then will just close this then.

**Pull request closed without merging**
