### PR TITLE
Put objtoolz in sandbox

### PR DESCRIPTION
**Pull request by berrytj**
This pull request adds assoc_obj, update_in_obj, and get_in_obj to the sandbox.

### CODE REVIEW

**Comment by radix** [comment]
by the way, is there any hope of this being added to toolz soon? it's been a while :)

**Comment by mrocklin** [comment]
I'm not certain that I want to extend `toolz` out to object land.  It's a large expansion of scope.

**Comment by mrocklin** [comment]
I'm going to close this pending an outcry that people really really want it.  

I'd also love to see `objtoolz` put in to a separate package.

**Comment by radix** [comment]
oh. well, put me down for a vote for objtoolz, whether in toolz or not. we need our pure objects just as we need our pure mappings :)

**Comment by radix** [comment]
@berrytj do you have any interest in creating a separate library for this?

**Comment by berrytj** [comment]
@radix not writing python at the moment, so unlikely.

**Pull request closed without merging**
