### PR TITLE
Add `apply`

### PR DESCRIPTION
**Pull request by eliasmistler**

### CODE REVIEW

**Comment by llllllllll** [comment]
I am +1 because this is generally useful and is duplicated in a lot of code; however, I somewhat object to the phrase "clojure-like": https://docs.python.org/2/library/functions.html#apply. Still very Pythonic.

**Comment by eriknw** [comment]
Yeah, I agree this is common enough to justify being added.

It's unfortunate that `apply` is no longer anywhere to be found in core Python.  The fatal flaw of the given implementation is that `func=` may not be used as a keyword.

What about something like this:
```python
def apply(*func_and_args, **kwargs):
    if not func_and_args:
        raise TypeError('func argument is required')
    return func_and_args[0](*func_and_args[1:], **kwargs)
```

**Comment by eliasmistler** [comment]
@eriknw Agree and updated

**Comment by eliasmistler** [comment]
@eriknw ready to merge as far as I'm concerned

**Comment by eriknw** [comment]
This is in, thanks @eliasmistler! (and sorry for the delay)

**Comment by Hugovdberg** [comment]
Just a remark perhaps for future reference, as of Python 3.8 the signature could be simplified once more by use of the positional only indicator:

```python
def apply(func, /, *args, **kwargs):
    return func(*args, **kwargs)

def test_no_keyword_clash(x, func):
    return x+func

apply(test_no_keyword_clash, x=1, func=2)
```

**Pull request merged**
